name: task1
description: First task for first lab for MIREA software development

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  intl_translation: ^0.17.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/gopher.png